version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/conf:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  sensors:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensors
    depends_on:
      - mosquitto
    # restart: always
    env_file:
      - .env